config/routes.rb
Rails.application.routes.draw do
	root 'homes#index'

  devise_for :users

  get 'home/about' => 'homes#show'
  resources :homes, only: [:index]
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    validates :name, presence: true, length: { in: 2..20 }
    validates :introduction, length: { maximum: 50 }

    has_many :books, dependent: :destroy
    attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		user_path(current_user.id)
	end

	def after_sign_out_path_for(resource)
		root_path
	end

	
	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :authenticate_user!
	before_action :correct_book, only: [:edit, :update]

	def index
		@book = Book.new
		@books = Book.all
		@user = current_user
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			redirect_to books_path, notice: 'You have creatad book successfully.'
		else
			@books = Book.all
			@user = current_user
			render :index
		end
	end

	def show
		@book = Book.new
		@book_show = Book.find(params[:id])
		@user = @book_show.user
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			redirect_to book_path(@book.id), notice: "You have updated book successfully."
		else
			render :edit
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	def correct_book
		book = Book.find(params[:id])
		if current_user.id != book.user_id
			redirect_to books_path
		end
	end

	private

	def book_params
		params.require(:book).permit(:title, :body)
	end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
	end

	def show
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
  	@users = User.all
  	@book = Book.new
  	@user = current_user
  end

  def show
  	@user = User.find(params[:id])
  	@book_show = @user.books
  	@book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
    @user.profile_image_id = current_user.id
  	if @user.update(user_params)
  	  redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def correct_user
    user = User.find(params[:id])
    if user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_side.html.erb
<div class="col-xs-3">
	<h2>User info</h2>
	<table class="table">
		<%= attachment_image_tag @user, :profile_image, size: "100x100", format: 'jpeg', fallback: "no_image.jpg" %>
		<tbody>
			<tr></tr>
			<tr>
				<th>name</th>
				<th><%= user.name %></th>
			</tr>
			<tr>
				<th>introducion</th>
				<th><%= user.introduction %></th>
			</tr>
		</tbody>
	</table>
	<div class="row">
		<%= link_to "", edit_user_path(user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
	</div>
	<h2>New book</h2>
	<%= form_for(book) do |f| %>
		<div class="field row">
			<label for="book_title">Title</label>
			<%= f.text_field :title, class: "col-xs-12 book_title" %>
		</div>
		<div class="field row">
			<label for="book_opinion">Opinion</label>
			<%= f.text_area :body, class: "col-xs-12 book_body" %>
		</div>
		<div class="row">
			<%= f.submit "Create Book", class: "btn btn-primary col-xs-12" %>
		</div>
	<% end %>
</div>

app/views/books/edit.html.erb
<p id="notice"><%= notice %></p>

<% if @book.errors.any? %>
	<div id="eroor_explanation">
		<h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
		<ul>
			<%= @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<div class="row">
	<div class="col-md-6">
		<h1>Editing Book</h1>
		<%= form_for(@book) do |f| %>
			<div class="field row">
				<label for="book_title">Title</label>
				<%= f.text_field :title, class: "col-xs-12" %>
			</div>
			<div class="field row">
				<label for="book_opinion">Opinion</label>
				<%= f.text_area :body, class: "col-xs-12" %>
			</div>
			<div class="actions row">
				<%= f.submit "Update Book", class: "btn btn-primary col-xs-12" %>
			</div>
		<% end %>
		<div>
			<%= link_to "Show", book_path(@book.id) %>
			 |
			<%= link_to "Back", books_path %>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<p class="notice"><%= notice %></p>

<% if @book.errors.any? %>
	<div id="eroor_explanation">
		<h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
		<ul>
			<%= @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<div class="row">

	<%= render 'books/side', book: @book, user: @user %>

	<div class="col-xs-9">
		<h2>Books</h2>
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Ttle</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<% @books.each do |book| %>
			<tbody>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book.id) %></td>
					<td><%= book.body %></td>
				</tr>
			</tbody>
			<% end %>
		</table>
	</div>
</div>

app/views/books/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<div class="row">

	<%= render 'books/side', book: @book, user: @user %>

	<div class="col-xs-9">
		<h2>Book detail</h2>
		<table class="table">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>
						<%= link_to user_path(@user.id) do %>
							<%= attachment_image_tag @user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %><p><%= @user.name %></p>
						<% end %>
					</td>
					<td><%= link_to @book_show.title, book_path(@book_show.id) %></td>
					<td><%= @book_show.body %></td>
					<% if @book_show.user == current_user %>
						<td><%= link_to "Edit", edit_book_path(@book_show.id), class: "btn-sm btn-success" %></td>
						<td><%= link_to "Destroy", book_path(@book_show), method: :delete, class: "btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %></td>
					<% end %>
				</tr>
			</tbody>
			<tbody></tbody>
		</table>
	</div>
</div>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
	<div class="top-message col-md-offset-3 col-md-6">
		<h1>welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong> !!</h1>
		<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers,</strong></p>
		<p>you can share and exchange your opinions , inpressions , and emotions</p>
		<p>about various books!</p>
		<div class="btn-wrapper">
			<div class="row">
				<p>
					<%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %>
				</p>
			</div>
			<div class="row">
				<p>
					<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
				</p>
			</div>
		</div>
	</div>
</div>

app/views/homes/show.html.erb
<h1>Welcome to <span class="glyphicon glyphicon-book"></span>Bookers!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers22</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <div class="conatainer">
          <nav class="nav navbar-nav navbar-left"><span>Bookers</span></nav>
        <nav class="row">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to "Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %>
              </li>
              <li>
                <%= link_to "Users", users_path, class: "glyphicon glyphicon-user" %>
              </li>
              <li>
                <%= link_to "Books", books_path, class: "glyphicon glyphicon-book" %>
              </li>
              <li>
                <%= link_to "logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %>
              </li>
            <% else %>
              <li>
                <%= link_to "Home", root_path, class: "glyphicon glyphicon-home home" %>
              </li>
              <li>
                <%= link_to "About", home_about_path, class: "glyphicon glyphicon-link about" %>
              </li>
              <li>
                <%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %>
              </li>
              <li>
                <%= link_to "login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <div class="container">

    <%= yield %>

    </div>

    <footer>
      <p>CopyRight Infratop.inc</p>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<% if @user.errors.any? %>
	<div id="eroor_explanation">
		<h2><%= @user.errors.count %>errors prohibited this obj from being saved:</h2>
		<ul>
			<%= @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<h2>User info</h2>
	<%= form_for(@user) do |f| %>
		<div class="field">
			<label for="user_name">Name</label>
			<%= f.text_field :name %>
		</div>
		<div class="field">
			<label for="user_image">Image</label>
			<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
		</div>
		<div class="field">
			<label for="user_introduction">Introduction</label>
			<%= f.text_area :introduction %>
		</div>
		<div class="actions">
			<%= f.submit "Update User" %>
		</div>
	<% end %>
</div>

app/views/users/index.html.erb
<p id="notice">
	<%= notice %>
</p>
<div class="row">

	<%= render 'books/side', book: @book, user: @user %>

	<div class="col-xs-9">
		<h2>Users</h2>
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<% @users.each do |user| %>
			<tbody>
				<tr>
					<td><%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
					<td><%= user.name %></td>
					<td><%= link_to "Show", user_path(user) %></td>
				</tr>
			</tbody>
			<% end %>
		</table>
	</div>

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<%= render 'books/side', book: @book, user: @user %>

	<deiv class="col-xs-9">
		<h2>Books</h2>
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<% @book_show.each do |book| %>
			<tbody>
				<tr>
					<td>
						<%= link_to user_path(book.user_id) do %>
							<%= attachment_image_tag @user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book.id) %></td>
					<td><%= book.body %></td>
				</tr>
			</tbody>
			<% end %>
		</table>
	</deiv>
</div>